class UnexpectedError(Exception): ...


class BadCredentialsError(Exception): ...


class AccessDeniedError(Exception): ...


class InvalidPasswordError(Exception): ...


class EntityDoesNotExistError(Exception): ...
